import { Inter } from 'next/font/google'
import '../styles/globals.css'
import NavbarPage from './componens/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayou ({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main>
          <NavbarPage />
          {children}
        </main>
      </body>
    </html>
  )
}
