import styles from './Home.module.css'
import data from '../data/teams.data.json'

export const metadata = {
  title: 'Tornapp',
  description: 'Generated by create next app'
}



export default function Home () {

  const team = data.teams[0]


  return (
    <div>
      <h1>Home Page </h1>

      <div>
        <h2>Mi Equipo</h2>
        <div className={ styles.myTeams}>
          <div className={ styles.teamData }>
            <img src={team.logo_path} alt="team logo"/>
            <h3 className={ styles.h3 }> { team.name } </h3>
            <span className={ styles.h3 }> { team.founded } </span>
          </div>
          <div className={ styles.teamStats }>
          <span className={ styles.h3 }> { team.pj } </span>
          <span className={ styles.h3 }> { team.pg } </span>
          <span className={ styles.h3 }> { team.pe } </span>
          <span className={ styles.h3 }> { team.pp } </span>
          </div>

        </div>
      </div>
      <div>
        <h2>Mis Torneos</h2>
        <div className={ styles.myTournaments}>

        </div>
      </div>
    </div>
  )
}
