'use client'
import { Button, 
         Form, 
         Input, 
         Label, 
         Select, 
         SelectContent, 
         SelectItem, 
         SelectTrigger, 
         SelectValue 
        } from "@/components/ui"

import styles from './create_team.module.css';

// export const metadata = {
//     title: 'Crear Equipo - TornApp',
//     description: 'Generated by create next app'
// }

export default function CreateTeamPage () {



return (
<div className={styles.container}>
    <h3 className={`text-white text-4xl font-bold mb-5 ${styles.h3}`}>CREAR EQUIPO</h3 >
        <Form className={ `flex flex-col space-y-5 ${styles.form} `}>
        <div className="grid w-full items-center gap-4">
            <div className={styles.name_div}>
                <div>
                    <Label className={styles.label} htmlFor="name" >NOMBRE</Label>
                    <Input id="name" placeholder="Nombre del equipo" className={ `${styles.input} ${styles.name}` } maxLength="18"/>
                </div>
                <div>
                    <Label className={styles.label} htmlFor="name" >ABREVIATURA</Label>
                    <Input
                        type="text"
                        name="abreviatura"
                        placeholder="ABC"
                        maxLength="3"
                        pattern="[a-zA-Z0-9]*"
                        className={`w-20 text-center font-bold tracking-widest ${styles.input}`}
                    />

                </div>
            </div>
            <div className="flex flex-col space-y-1.5">
                <Label className={styles.label} htmlFor="year" >AÑO DE FUNDACIÓN</Label>
                <Select>
                    <SelectTrigger id="framework" className='w-20' >
                    <SelectValue placeholder={new Date().getFullYear()} />
                    </SelectTrigger>
                    <SelectContent position="popper">
                    {[...Array(new Date().getFullYear() - 1899)]
                    .map((_, index) => new Date().getFullYear() - index)
                    .map((year, index) => (
                        <SelectItem value={year} key={year}>{year}</SelectItem>
                    ))}
                    <SelectItem value="sveltekit">SvelteKit</SelectItem>
                    <SelectItem value="astro">Astro</SelectItem>
                    <SelectItem value="nuxt">Nuxt.js</SelectItem>
                    </SelectContent>
                </Select>
            </div>
            <Button className={`dark text-white w-40 center m-auto`} variant="outline">
                CREAR
            </Button>
        </div>
        </Form>

        


</div>
)
}
